force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Fees__c</fullName>
        <label>Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hyderabad</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Pune</fullName>
                </value>
                <value>
                    <fullName>Chennai</fullName>
                </value>
                <value>
                    <fullName>Mumbai</fullName>
                </value>
                <value>
                    <fullName>Gurgaon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Course__c</fullName>
        <label>Total Course</label>
        <summaryForeignKey>Registration__c.Student__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Student Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RegisteredStudentList.cls
public class RegisteredStudentList {
  // wrapper list
   public list<stdWrapper> stdListWrapper{get;set;}
    
    //constructor
    public RegisteredStudentList(){
    
    // query for student ( inner query for registration(course)  and Fee
        list<student__c> stdList=[select id,name,City__c,Date_Of_Birth__c,(select id,course__r.Fees__c,course__r.Name from Registrations__r),(select id,Amount__c from Fees__r) from student__c where Total_Course__c>0];
        
        // wrapper all value
        stdListWrapper= new List<stdWrapper>();
        double pd=0, payb=0, rem=0;
        
        // courses string
        string courseDet='[ ';
        for(student__c std:stdList){
            stdWrapper stw= new stdWrapper();
            for(Registration__c reg: std.Registrations__r){
                //payable amount
                payb +=reg.course__r.Fees__c;
                // courses string
               courseDet+=reg.course__r.Name +'--> Rs.'+reg.course__r.Fees__c+', ';
                }
                courseDet= courseDet.removeEnd(', ');
                courseDet+=' ]';
            
             //paid fees   
            for(Fee__c fe: std.Fees__r)
                pd += fe.Amount__c;
            
            // remaining
            rem=payb-pd;
            stw.stud=std;
            stw.payable=payb;
            stw.paid=pd;
            stw.remain=rem;
            stw.crsDet=courseDet;
            // adding this wrapper into list
            stdListWrapper.add(stw);
        }
    }
    // wrapper class
    public class stdWrapper{
        public student__c stud{get;set;}
        public string crsDet{get;set;}
        public double payable{get;set;}
        public double paid{get;set;}
        public double remain{get;set;}
    }
    // code s'f 
}

/*
 
public class RegStuList {
    
  // wrapper list
   public list<stdWrapper> stdListWrapper{get;set;}
    
    //constructor
    public RegStuList(){
    
    // query for student ( inner query for registration(course)  and Fee
        list<student__c> stdList=[select id,name,City__c,Date_Of_Birth__c,(select id,course__r.Fees__c,course__r.Name from Registrations__r) from student__c where Total_Course__c>0];
        set<id> stdSet= new set<id>();
        Map<id, double> stdPaidMap= new Map<id, double>();
        for(student__c std:stdList)
            stdSet.add(std.id);

         for(AggregateResult agR: [SELECT student__c, sum(Amount__c) totalfee FROM Fees__c where student__c IN:stdSet GROUP BY student__c])
                stdPaidMap.put(string.valueOf(agR.get('student__c')), Double.valueOf(agR.get('totalfee')));
          
        // wrapper all value
        stdListWrapper= new List<stdWrapper>();
        
        for(student__c std:stdList){
        double pd=0, payb=0, rem=0;
       
            stdWrapper stw= new stdWrapper();
             // courses string
        string courseDet='[ ';
        
            for(Registration__c reg: std.Registrations__r){
                //payable amount
                payb +=reg.course__r.Fees__c;
                // courses string
                courseDet+=reg.course__r.Name+' --> '+reg.course__r.Fees__c+', ';
                }
            courseDet= courseDet.removeEnd(', ');
            courseDet+=' ]';
                
            if(stdPaidMap.containsKey(std.id))
                pd=stdPaidMap.get(std.id);

            // remaining
            rem=payb-pd;
            
            stw.stud=std;
            stw.payable=payb;
            stw.paid=pd;
            stw.remain=rem;
            stw.crsdt=courseDet;
            
            // adding this wrapper into list
            stdListWrapper.add(stw);
                
        }  
    }
    // wrapper class
    public class stdWrapper{
        public student__c stud{get;set;}
       // public string crsDet{get;set;}
       public string crsdt {get;set;} 
        public double payable{get;set;}
        public double paid{get;set;}
        public double remain{get;set;}
       
    }
}*/