force-app/main/default/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoices__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice_Customer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerAdd.cls
public class CustomerAdd {
    public static void CustomerAddress(List<Invoices__c> newInvoice){
            	Set<ID> CustId = New Set<ID>();
				List<Customer__c> Cust = new List<Customer__c>();
	    	    for(Invoices__c Inv : newInvoice){
     				CustId.add(Inv.Customer_Name__c);
     }
     Map<ID,Customer__c> CustMap = New Map<ID,Customer__c>([SELECT id,ADDRESS__c from 
     Customer__c where ID in :CustId]);
    for(Invoices__c Inv1 : newInvoice){
        Inv1.Address__c=CustMap.get(Inv1.Customer_Name__c).Address__c;
    }
    
    }
}



/*below method not bulkified
    public static void UpdateCustmeradrs(List<Invoices__c> newInvoice)
    {
		Invoices__c firstInvoice  = newInvoice[0];
       Customer__c cst=[SELECT id,ADDRESS__c from Customer__c where ID =:firstInvoice.Customer_Name__c];
        
    }*/