force-app/main/default/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Salary_Offered__c</fullName>
        <label>Salary Offered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>experience_in_years__c</fullName>
        <label>experience in years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SalaryOffer.cls
public class SalaryOffer {
     public static void Exp(list<Job_Application__c> newJobApp){
           for(Job_Application__c JobApp :newJobApp){
               if (JobApp.experience_in_years__c <4) {
                   JobApp.Salary_Offered__c=5000;
       }
       else if (JobApp.experience_in_years__c >= 4 && JobApp.experience_in_years__c < 6)
       {
           JobApp.Salary_Offered__c = 7000;
       } 
           else JobApp.salary_offered__c = 10000;
   }
  }
}