force-app/main/default/objects/Moblie__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apple</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>Sony</fullName>
                </value>
                <value>
                    <fullName>Samsung</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Moblie</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Moblie Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestClass.cls
@isTest
    public class TestClass{
        public static testMethod void testFunction(){
        // create new record data
            Moblie__c mob = new Moblie__c();
                mob.Brand__c= 'Apple';
                    mob.Price__c=1000;
                        system.debug('Price before insert is :' + mob.price__c);
                             //expected is 1000
                                 // insert the new record
                            insert mob;
                         //trigger will come into picture and give a discount of 25 percent
                    //retrieve the new price
                Moblie__c mob1=[select price__c from Moblie__c where id=:mob.id];
            system.debug('Proce after the trigger is fired is :' + mob1.Price__c);
        // expected is 750
    //Test that the trigger is fired and did correct calculations
system.assertEquals(750, mob1.price__c);
        }
        
 public static testMethod void testFunction1(){
        // create new record data
            Moblie__c mob = new Moblie__c();
                mob.Brand__c= 'LG';
                    mob.Price__c=1100;
                        system.debug('Price before insert is :' + mob.price__c);
                             //expected is 1100
                                 // insert the new record
                            insert mob;
                         //trigger will come into picture and give a discount of 10 percent
                    //retrieve the new price
                Moblie__c mob1=[select price__c from Moblie__c where id=:mob.id];
            system.debug('Proce after the trigger is fired is :' + mob1.Price__c);
        // expected is 990
    //Test that the trigger is fired and did correct calculations
system.assertEquals(990, mob1.price__c);
        }
 public static testMethod void testFunction2(){
        // create new record data
            Moblie__c mob = new Moblie__c();
                mob.Brand__c= 'Samsung';
                    mob.Price__c=800;
                        system.debug('Price before insert is :' + mob.price__c);
                             //expected is 800
                                 // insert the new record
                            insert mob;
                         //trigger will come into picture and give a discount of 50 percent
                    //retrieve the new price
                Moblie__c mob1=[select price__c from Moblie__c where id=:mob.id];
            system.debug('Proce after the trigger is fired is :' + mob1.Price__c);
        // expected is 400
    //Test that the trigger is fired and did correct calculations
system.assertEquals(400, mob1.price__c);
        }


}