force-app/main/default/objects/Moblie__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apple</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>Sony</fullName>
                </value>
                <value>
                    <fullName>Samsung</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Moblie</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Moblie Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/discount.cls
public class discount{
    public static void disc(list<Moblie__c> NewDiscount){
        for(Moblie__c Dis :NewDiscount){
            if (Dis.Brand__c=='Apple'){
                 Dis.Price__c= (Dis.Price__c - (Dis.Price__c*25/100));}
            {
            if (Dis.Brand__c=='LG'){
                 Dis.Price__c= (Dis.Price__c - (Dis.Price__c*10/100));}
        }
        {
            if (Dis.Brand__c=='Samsung'){
                 Dis.Price__c= (Dis.Price__c - (Dis.Price__c*50/100));}}
}
}
}